Update deploy-ec2.yml

diff --git a/.github/workflows/deploy-ec2.yml b/.github/workflows/deploy-ec2.yml
--- a/.github/workflows/deploy-ec2.yml
+++ b/.github/workflows/deploy-ec2.yml
@@ -1,4 +1,65 @@
+name: Deploy to EC2
 
 on:
   push:
     branches: ["master"]
+
+jobs:
+  deploy:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      # (Opcional) Se quiser manter: ajuda a evitar "Host key verification failed"
+      - name: Add EC2 host to known_hosts
+        run: |
+          mkdir -p ~/.ssh
+          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts
+      - name: Deploy via SSH
+        uses: appleboy/ssh-action@v1.1.0
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USER }}   # admin
+          port: 22
+          key: ${{ secrets.EC2_SSH_KEY }}     # ✅ PEM cru aqui (BEGIN...END)
+          script_stop: true
+          debug: true
+          script: |
+            set -e
+            cd /opt/hello-devops
+            git fetch origin
+            git reset --hard origin/master
+            
+              # remove qualquer container usando a porta 80
+                PORT80_CONTAINERS=$(docker ps -q --filter "publish=80" || true)
+                if [ -n "$PORT80_CONTAINERS" ]; then
+                  docker rm -f $PORT80_CONTAINERS || true
+                fi
+           
+                  docker build -t hello-devops:latest .
+                  
+                  # Remove o container antigo (se existir) sem poluir o log
+                  docker rm -f hello-devops 2>/dev/null || true
+                  
+                  docker run -d --name hello-devops --restart unless-stopped -p 80:3000 hello-devops:latest
+                  
+                  docker ps
+                  
+                  # Espera a app subir (retry por ~30s)
+                  for i in {1..15}; do
+                    if curl -fsSI http://localhost:80 >/dev/null; then
+                      echo "Aplicação OK na porta 80"
+                      break
+                    fi
+                    echo "Aguardando aplicação subir... tentativa $i/15"
+                    sleep 2
+                  done
+                  
+                  # Se ainda falhar, mostrar logs e retornar erro
+                  if ! curl -fsSI http://localhost:80; then
+                    echo "Falhou healthcheck. Logs do container:"
+                    docker logs --tail 200 hello-devops || true
+                    exit 1
+                  fi
